### ISSUE TITLE
Visual Studio Test Adapter - Writing to test output throws an error

### ISSUE THREAD

**Issue by Slimfit** [nunit/docs#106]
I am using NUnit nuget package 3.4.1 with NUnit 3 Test adapter 3.4.1. 
The following test:

```
[Test]
public void Test()
{
    Debug.WriteLine("DEBUG");
    Console.WriteLine("CONSOLE");
    Trace.WriteLine("TRACE");
 }
```

will output this in the "Show output from Tests" window:

> ------ Discover test started ------
NUnit Adapter 3.4.1.0: Test discovery starting
NUnit Adapter 3.4.1.0: Test discovery complete
========== Discover test finished: 5 found (0:00:00.2279294) ==========
------ Run test started ------
NUnit Adapter 3.4.1.0: Test execution started
Running selected tests in C:\Code\mydll.dll
NUnit3TestExecutor converted 5 of 5 NUnit test cases
D
E
B
U
G
Error processing test-output event for 
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Core.Logging.TestRunMessageLoggerProxy.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestOutput(XmlNode outputNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
Error processing test-output event for 
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Core.Logging.TestRunMessageLoggerProxy.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestOutput(XmlNode outputNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
T
R
A
C
E
Error processing test-output event for 
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Core.Logging.TestRunMessageLoggerProxy.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestOutput(XmlNode outputNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
Error processing test-output event for 
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Core.Logging.TestRunMessageLoggerProxy.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestOutput(XmlNode outputNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
NUnit Adapter 3.4.1.0: Test execution complete
========== Run test finished: 1 run (0:00:12.6423955) ==========

**Comment by CharliePoole** [comment]
It's an interesting problem. NUnit actually does nothing special for Debug and Trace output, so I'm not clear how the TestOutput event handler is activated.

Since you say you are using the NUnit 3 Adapter, I'm moving this issue to that repository. This is the repository for NUnit documentation.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit3-vs-adapter #220](https://github.com/nunit/nunit3-vs-adapter/issues/220) via [**ZenHub**](https://www.zenhub.com/)
