### ISSUE TITLE
Failed Test Notification to "Author" through Octopus Deploy

### ISSUE THREAD

**Issue by mcgary-andrew** [nunit/docs#279]
How can we use the "Author" attribute to send an email to the author of a failed test? We run our tests through Octopus Deploy, and if there is a failed test, I would like author of the test to be emailed.

Thanks!

**Comment by mikkelbu** [comment]
I don't think that there is anything out-of-the-box that you can use (at least nothing I know about). But if you have added `Author` to some of the tests or fixtures then after a test-run with failing tests you could
* examine the resulting XML
* find the failing tests/testfixtures
* extract the author information from the test/fixture (it will be in a `property` element with `name` attribute containing `"Author"` and the `value` attribute containing name + possible email.
* email the author (using some external functionality)

And example XML could look like this
```xml
...
<test-case id="0-1002" name="Test2" fullname="AuthorAttributeTest.Class1.Test2" methodname="Test2" classname="AuthorAttributeTest.Class1" runstate="Runnable" seed="368513389" result="Failed" start-time="2018-08-17 18:58:25Z" end-time="2018-08-17 18:58:25Z" duration="0.017044" asserts="0">
  <properties>
    <property name="Author" value="Jane Doe" />
    <property name="Author" value="John Doe &lt;my.email@example.com&gt;" />
  </properties>
  <failure>
    <stack-trace><![CDATA[   at AuthorAttributeTest.Class1.Test2()
]]></sck-trace>
  </failure>
  <assertions>
    <assertion result="Failed">
      <message><![CDATA[]]></message>
      <stack-trace><![CDATA[   at AuthorAttributeTest.Class1.Test2()
]]></sck-trace>
    </assertion>
  </assertions>
</test-case>
...
```

**Comment by ocmyhome** [comment]
When adding the [Author] attribute to the TestFixture I'm finding when I get the properties bag that "Author" isn't included.  I've tried a couple different ways of accessing this property/value:

.Test.Properties.Get("Author");
.Test.Properties;

Neither of which show this attribute.

I'm trying to view this attribute in the AfterEach step of the test.

Thoughts?

**Comment by jnm2** [comment]
@ocmyhome Properties don't cascade, so at the moment you have to manually loop through all direct ancestor tests to collect a list of applicable authors.

**Comment by CharliePoole** [comment]
If the property is on the fixture, you can access it in OneTimeSetUp or OneTimeTearDown.

**Comment by mcgary-andrew** [comment]
I am adding an Author Property on the TestFixture, but it is not being captured on my OneTimeTearDown, if I put the Author on the actual Test it works. I would rather be able to put the author on the test fixture than putting it on every single test we have.

**Comment by mikkelbu** [comment]
Hi @mcgary-andrew 
It is working on my machine (newest framework and run from VS). In the following I get the string `None` in the file `C:\temp\Author.txt` when the `OneTimeTearDown` has run.
```c#
[TestFixture]
[Author("None")]
public class AuthorTest
{
    [OneTimeTearDown]
    public void TearDown()
    {
        var author = (string)TestContext.CurrentContext.Test.Properties.Get("Author");
        File.WriteAllText(@"C:\temp\Author.txt", author);
    }

    [Test]
    public void Test()
    {
    }
}
```
